import Link from "next/link";
import { PageShell } from "@/components/PageShell";

export default function PrivacyPage() {
  return (
    <PageShell
      title="privacy"
      intro="What we collect, how we use it, and what we don't do with your information. Last updated August 2026."
    >
      <div className="space-y-8">
        <section className="space-y-3">
          <h2>What we collect</h2>
          <p>
            When you submit a store, we collect the information needed to
            create and manage your listing, including your store name, domain,
            category, description, and bid amount.
          </p>
          <p>
            We also collect a contact email so we can communicate with you
            about your listing, payments, and account-related questions.
          </p>
          <p>
            When you place or change a bid, we record the bid amount and the
            time it was placed.
          </p>
        </section>

        <section className="space-y-3">
          <h2>What's public</h2>
          <p>
            Information displayed as part of your store listing is publicly
            visible on Outbid.store. This may include your store name, website,
            category, description, rank, and current bid.
          </p>
          <p>
            Your contact email and other information that isn't part of your
            public listing are not displayed to other stores or visitors.
          </p>
        </section>

        <section className="space-y-3">
          <h2>How we use your information</h2>
          <p>
            We use the information we collect to operate Outbid.store, process and
            manage bids, maintain store listings, communicate with store
            owners, prevent abuse, and improve the service.
          </p>
          <p>
            We may also use aggregated or de-identified information to
            understand how the board is being used and how much traffic
            different positions generate.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Analytics</h2>
          <p>
            We track visits to Outbid.store and interactions with listed stores,
            including clicks from the board to store websites. This helps us
            understand how the service is performing and gives us insight into
            the traffic generated by different positions.
          </p>
          <p>
            We do not use analytics to sell individual visitor profiles to
            advertisers.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Payments</h2>
          <p>
            Payments are processed by our payment provider. We do not need to
            store your full payment card details to operate your listing.
            Payment providers may collect and process information according to
            their own privacy policies.
          </p>
        </section>

        <section className="space-y-3">
          <h2>What we don't do</h2>
          <p>
            We do not sell your personal information to third parties. We do
            not share your contact email with other stores on the board for
            marketing purposes.
          </p>
          <p>
            We do not use your private contact information to build or sell
            advertising profiles.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Cookies</h2>
          <p>
            We may use cookies or similar technologies that are necessary for
            the site to function, such as maintaining sessions and remembering
            preferences.
          </p>
          <p>
            We do not use cookies for cross-site advertising or behavioral ad
            tracking.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Third-party services</h2>
          <p>
            Outbid.store may rely on third-party providers for services such as
            payments, hosting, analytics, email, and security. These providers
            may process information on our behalf as necessary to provide their
            services.
          </p>
        </section>

        <section className="space-y-3">
          <h2>How long we keep information</h2>
          <p>
            We keep information for as long as reasonably necessary to operate
            the service, maintain transaction and business records, resolve
            disputes, prevent abuse, and comply with legal obligations.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Your requests</h2>
          <p>
            You can contact us to request access to, correction of, or removal
            of information associated with your store, subject to information
            we may need to retain for legal, security, or transaction
            purposes.
          </p>
          <p>
            To make a request, use the{" "}
            <Link href="/contact" className="underline">
              contact page
            </Link>
            .
          </p>
        </section>

        <section className="space-y-3">
          <h2>Changes to this policy</h2>
          <p>
            We may update this privacy policy as Outbid.store changes. When we make
            changes, we'll update the date at the top of this page. Your
            continued use of Outbid.store after an update means you acknowledge the
            revised policy.
          </p>
        </section>

        <section className="space-y-3">
          <h2>Contact</h2>
          <p>
            If you have questions about this privacy policy or how your
            information is handled, please reach out through the{" "}
            <Link href="/contact" className="underline">
              contact page
            </Link>
            .
          </p>
        </section>
      </div>
    </PageShell>
  );
}
